/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LiczImport } from './routes/licz'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const LiczRoute = LiczImport.update({
  path: '/licz',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/licz': {
      id: '/licz'
      path: '/licz'
      fullPath: '/licz'
      preLoaderRoute: typeof LiczImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ IndexRoute, LiczRoute })

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/licz"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/licz": {
      "filePath": "licz.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
